# SPDX-FileCopyrightText: 2025 Javier Pérez
#
# SPDX-License-Identifier: CC0-1.0

name: Mirror GitLab repository

on:
  schedule:
    - cron: "0 * * * *"

permissions:
  contents: read

jobs:
  mirror-gitlab-repo:
    runs-on: ubuntu-22.04
    env:
      GIT_LFS_VERSION: "3.6.1"
      GIT_LFS_SHA256: "2138d2e405a12f1a088272e06790b76699b79cb90d0317b77aafaf35de908d76"
    steps:
      - name: Download and move Git LFS
        run: |
          wget https://github.com/git-lfs/git-lfs/releases/download/v${GIT_LFS_VERSION}/git-lfs-linux-amd64-v${GIT_LFS_VERSION}.tar.gz
          echo "${GIT_LFS_SHA256}  git-lfs-linux-amd64-v${GIT_LFS_VERSION}.tar.gz" | sha256sum --check --strict
          tar xzf git-lfs-linux-amd64-v${GIT_LFS_VERSION}.tar.gz
          mv git-lfs-${GIT_LFS_VERSION}/git-lfs /usr/local/bin/

      - name: Configure Git LFS
        run: git lfs install

      - name: Clone upstream master
        run: git clone --branch master https://gitlab.com/veloren/veloren.git source

      - name: Migrate LFS
        working-directory: ./source
        timeout-minutes: 30
        run: |
          git lfs uninstall
          git lfs migrate export --verbose --include="*" --everything --skip-fetch --yes 2>&1

      - name: Push mirror to fork main
        working-directory: ./source
        env:
          MIRROR_TOKEN: ${{ secrets.MIRROR_TOKEN_GITHUB }}
        run: |
          export GIT_CONFIG_COUNT=1
          export GIT_CONFIG_KEY_0=http.https://github.com/.extraheader
          export GIT_CONFIG_VALUE_0="AUTHORIZATION: bearer ${MIRROR_TOKEN}"
          git remote set-url origin "https://github.com/${GITHUB_REPOSITORY}.git"
          GIT_TERMINAL_PROMPT=0 git push --force --tags origin HEAD:refs/heads/main
